import numpy

GRAV_X = 0
GRAV_Y = 0
GRAV_Z = -9.8

SIM_STEPS = 1000
SIM_TIME_SLEEP = 0.01

BACKLEG_AMPLITUDE = numpy.pi / 4
BACKLEG_FREQUENCY = 10
BACKLEG_PHASE_OFFSET = 0
BACKLEG_MAX_FORCE = 50

FRONTLEG_AMPLITUDE = numpy.pi / 4
FRONTLEG_FREQUENCY = 10
FRONTLEG_PHASE_OFFSET = 0
FRONTLEG_MAX_FORCE = 50